version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        networks:
            - app-network
        restart: unless-stopped

    frontend:
        build:
            context: ./client
        ports:
            - "80:80"
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
