version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        networks:
            - app-network
        restart: unless-stopped
        volumes:
            - ./backend:/app

    frontend:
        build:
            context: ./client
        ports:
            - "3000:3000"
        networks:
            - app-network
        restart: unless-stopped
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true

networks:
    app-network:
        driver: bridge
