[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://reviewandstorelocator.onrender.com/api/:splat"
  status = 200
